### ISSUE TITLE
Add body for overwritten methods for animals

### ISSUE THREAD

**Issue by osamahan999** [ayesha1/ZooSystem#1]
Animal class inherits the three interfaces AnimalActions.java, AnimalEmployeeInteract.java, and AnimalVisitorInteract.java. These three interfaces together produce seven methods:
talk(), move(), eat(), clean(), feed(), play(), feedSnack(). Need to overwrite the methods for each animal and write something for each animal.

**Comment by jungledesh** [comment]
completed this issue, please check PR and let me know
